# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='Phone_Number',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
