# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181128_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
