# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181128_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='acknowledgment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
