# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181202_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='acknowledgment',
            field=models.BooleanField(default=True),
        ),
    ]
