# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181205_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='generatedVerificationCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='userVerificationCode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
